- proposals/generic-values-and-valueof-for-enums.md
'Generic values() and valueOf() for enums' commit update
> 'Generic values() and valueOf() for enums' commit update

- proposals/stdlib/success-or-failure.md
> Fix spelling. Parametrizing -> Parameterizing

- proposals/unsigned-types.md
Discussion goes in [KEEP-135](https://github.com/Kotlin/KEEP/issues/135)
> Unsigned types

- proposals/stdlib/success-or-failure.md
Discussion of this proposal is held in [this issue](https://github.com/Kotlin/KEEP/issues/127).
> Encapsulate successful or failed function execution

- proposals/kotlin-contracts.md
Discussion goes in [KEEP-139](https://github.com/Kotlin/KEEP/issues/139)
> Proposal: Kotlin Contracts

- proposals/extensions/serialization.md
> Kotlin serialization compiler plugin

- proposals/jvm-field-annotation-in-interface-companion.md
This in an issue to discuss proposal for @JvmField for interface companion properties (PR #153).
> @JvmField for interface companion properties

- proposals/stdlib/durations-and-clocks.md
Discussion goes in [KEEP-190](https://github.com/Kotlin/KEEP/issues/190)
> Proposal: Duration and time measurement API

- proposals/scripting-support.md
"This would also allows" -> "This would also allow"
> A typo fixed

- proposals/jvm-records.md
Discussion goes in [KEEP-233](https://github.com/Kotlin/KEEP/issues/233).
Please don't use this pull request for questions, only for suggestions how to improve the text.
> JVM records support: proposal text

- proposals/sealed-class-inheritance.md
- proposals/sealed-interface-freedom.md
Please comment and suggest specific changes in the text in this PR. For general discussion, there is issue #226
> Sealed interfaces and sealed classes freedom

- proposals/sealed-interface-freedom.md
Describes interaction of sealed classes and interfaces with expect/actual declarations
> Expect sealed in multiplatform

- notes/value-classes.md
* fixed a few grammatical errors.
> grammar fixes

- proposals/unsigned-types.md
Clarify some use cases and non-goals of KEEP-#135.
> Clarifications about unsigned types use cases

- proposals/annotation-instantiation.md
Allow calling constructors of annotation classes in arbitrary code
to obtain an instance of a particular annotation class.
> Instantiation of annotation classes

- proposals/repeatable-annotations.md
Discussion of the proposal: #257.
Please comment on this pull request only with suggestions how to improve the proposal text. It will be merged in a few days.
> Repeatable annotations (#257)

- proposals/context-receivers.md
Discussion goes in [KEEP-259](https://github.com/Kotlin/KEEP/issues/259).
Please don't use this pull request for questions, only for suggestions on how to improve the text.
> Context receivers (#259)

- proposals/opt-in.md
See internal reference to Slack discussion in https://youtrack.jetbrains.com/issue/KT-49424 for original details.
> OptIn KEEP update (1.6.0 and 1.6.20 changes)

- proposals/opt-in.md
See details in https://youtrack.jetbrains.com/issue/KT-48890
> OptIn: KT-48890 related changes

- proposals/stdlib/durations-and-time-measurement.md
This PR updates the proposal text to include a section about value class-based time marks returned by the default monotonic time source.
> Add a section about specialized value time marks

- proposals/statics.md
> Fix statics.md

- proposals/stdlib/durations-and-time-measurement.md
This PR updates the proposal text with the changes describing comparable time marks introduced as experimental in Kotlin 1.8.0.
You can also find a short overview in What's new: https://kotlinlang.org/docs/whatsnew18.html#comparable-and-subtractable-timemarks
> Describe comparable time marks and their use cases

- proposals/open-ended-ranges.md
Discussion goes in [KEEP-314](https://github.com/Kotlin/KEEP/issues/314)
> Open-ended ranges and rangeUntil operator proposal

- proposals/dollar-escape.md
Only comment here about the text itself. This discussion about the feature itself takes place in [this issue](https://github.com/Kotlin/KEEP/issues/375).
> Multi-dollar interpolation

- proposals/stdlib/uuid.md
Only comment here about the text itself. The discussion about the feature is done in https://github.com/Kotlin/KEEP/issues/382.
This KEEP proposes to introduce a common UUID API in the Kotlin Standard Library.
> Uuid proposal

- proposals/annotation-target-in-properties.md
- proposals/change-defaulting-rule.md
Only comment here about the text itself. The discussion of the feature is done in #402.
> Improvements to annotation use-site targets on properties

- proposals/stdlib/instant.md
See https://kotlinlang.org/docs/whatsnew2120.html#new-time-tracking-functionality
> Update the status of the kotlin.time.Instant proposal

- proposals/stdlib/common-atomics.md
Functions were originally requested in [KT-76389](https://youtrack.jetbrains.com/issue/KT-76389) and will be added to 2.2.20.
> Add information about update-functions introduced in 2.2.20
