proposals/stdlib/map-copying.md
Introduce extensions for map to copy its content to another map.
=> Extensions to copy maps

proposals/scope-control-for-implicit-receivers.md
When we nest builders of different types into one another, members of the outermost implicit receiver are available in the innermost lambda (unless they are shadowed by something in inner lambdas):
``` kotlin
table {
tr {
tr {} // PROBLEM: Table.tr() is available here, 
// because the implicit receiever of `table {}` is in scope
}
}
```
Sometimes this effect is useful (the outermost receiver may provide some "global" services relevant to all necessary scopes, e.g. some context-like data), but often times it's problematic.
=> Scope control for implicit receivers

proposals/generic-values-and-valueof-for-enums.md
Generic operations on enums naturally involve retrieving all enum values or converting a string into a value. Example:
``` kotlin
// Print options on the screen
fun <reified T : Enum<T>> renderOptions(render: (T) -> String) {
val values = /* get T.values() somehow */
for (v in values) {
println(" * " + render(v))
}
}
```
Currently, there's no performant way of retrieving `values()`/`valueOf()` from an enum that is given as a generic parameter. This can be done through reflection, but it would be too slow for many use cases.
> The initial YouTrack issue: 
> - _[KT-10569](https://youtrack.jetbrains.com/issue/KT-10569) Cannot iterate over values of an enum class when it is used as a generic parameter_  
We propose to support `values()`/`valueOf()` for reified type parameters that extend …
=> Generic values() and valueOf() for enums

proposals/stdlib/bignumber-operations.md
The change in the convention for the `%` operator was introduced in v1.1
=> Updated for `%` to mean `rem` instead of `mod`

proposals/opening-classes-for-frameworks.md
Kotlin has classes and their members `final` by default. This has been causing debates that are summarized in [this forum post](https://discuss.kotlinlang.org/t/a-bit-about-picking-defaults/1418). While all the reasoning behind this default remains valid, there are use cases that tend to be painful, most notable are frameworks using CGLib proxies (e.g. Spring AOP, Mockito) and Gradle that decorates task classes at runtime.
We propose to enable a compilation strategy that does not classes and their members `final` if they are marked with framework-specific annotations, such as `@Service`, `@Repository`, `@Bean`,  `@Configuration`.
Open issues:
=> Opening classes for frameworks

proposals/android-extensions-entity-caching.md
There was a small inconsistency in the code. All 'entityView' fields were renamed to 'containerView' recently, except the one in the LayoutContainer snippet.
=> Renamed an old  'entityView' to 'containerView'

README.md
The link for getting an invite for kotlinlang Slack doesn't work: this PR should fix that.
=> correct kotlinlang slack invitation link

proposals/experimental.md
Because code is easier to read with syntax highlighting, right?
=> Add kotlin modifier to snippets for syntax colors

proposals/inline-classes.md
Discussion of this proposal is held in [this issue](https://github.com/Kotlin/KEEP/issues/104).
=> Inline classes

proposals/stdlib/random.md
Discussion goes in [KEEP-131](https://github.com/Kotlin/KEEP/issues/131)
=> Random API proposal

proposals/stdlib/success-or-failure.md
Looks like the return type of `findUserByName` is wrong in the sealed class example. Should be `FindUserResult` instead of `UserResult`.
=> [SuccessOrFailure] Fixed return type of findUserByName in the sealed class example

proposals/explicit-api-mode.md
replaced experimental API declarations with _opt-in requirements_ according to renaming in 1.3.70:
- `@Experimental` -> `@RequiresOptIn`
- `@UseExperimental` -> `@OptIn`
- `-Xuse-experimental` -> `-Xopt-in`
- changed `experimental` to `reqiuring opt-in` and similar throughout the text.
=> Actualize Experimental API in Explicit API mode with new annotation names

proposals/coroutines.md
I assume _suspending_ lambdas may invoke suspending functions whenever they want.
=> Fix a note about lambdas and suspending functions in KEEP

proposals/stdlib/result.md
Changing the name of the variable in the comment `first` to `result`.
=> Updating confusing comment on Result/Limitations

notes/value-classes.md
Taking into account use-cases where a value class is used as an immutable handle into a mutable data structure and the need to gradually teach developers new features where properties of immutable classes are somehow updated, we've decided to give an explicit name to the corresponding concept -- a "copyable property", and introduce a corresponding `copy` modifier both for "copyable properties" (`copy var`) and for copying functions (`copy fun`).
The text was updated to consistently use the corresponding terminology and the `copy` modifier. Motivation for the change was added to the text, too.
Restriction on the use of `var` properties for value classes is removed.
=> Introduce an explicit `copy var` notation

proposals/stdlib/result.md
* **Kotlin 1.5**
* Allow returning the `Result` type from functions.
* Allow Kotlin null-safety operators `?.`, `?:` and `!!` on both nullable and non-null `Result` types.
* Text updated to replace `inline class` with `@JvmInline value class`.
=> Revise Result type for Kotlin 1.5, remove restrictions

proposals/context-receivers.md
The current sample for contextual functional types seems incorrect since we do not support and do not propose the support of callable references for member extensions. I believe the new one shows the same and compiles.
=> Context receivers: fix functional types sample

proposals/explicit-backing-fields.md
The variable should be var to have setter
=> Explicit Backing Fields: Fixed typo

proposals/coroutines.md
The changed sentence doesn't make sense. I think removing the `coroutine` fixes it.
=> Fix a small typo in Coroutines proposal

notes/web-workers.md
It probably meant referring to `$captured.bar`, since there is no `$data` in scope
=> Fix typo in fragment with converted code example

proposals/coroutines.md
`kotlinx.coroutines` -> `kotlin.coroutines`
=> Fix package name that contains `Continuation` def

.gitattributes
This makes them show up in the language bar following the precedent of similar repos like [`swift-evolution`](https://github.com/apple/swift-evolution):
=> Mark Markdown files as `linguist-detectable`

proposals/stdlib/hex-format.md
Conversion functions return the type they convert to instead of a string
=> Fix typo in hex format proposal

proposals/context-parameters.md
Only comment here about the text itself. The discussion about the feature is done in [this issue](https://github.com/Kotlin/KEEP/issues/367).
This is an updated proposal for [KEEP-259](https://github.com/Kotlin/KEEP/issues/259), formerly known as _context receivers_. The new design addresses the issues raised by the users of the prototype and across the community.
=> Context parameters

proposals/stdlib/base64.md
Only comment here about the text itself. The discussion about the feature is done in https://github.com/Kotlin/KEEP/issues/373.
This KEEP proposes to introduce a multiplatform API for Base64 encoding and decoding.
=> Base64 proposal

proposals/coroutines.md
In `coroutines.md`, the internal link to the "coroutine builders" section was incorrectly written as `[coroutine builders](coroutine-builders)`,  
which does not work because it lacks the `#` symbol required for internal navigation.
- Changed `[coroutine builders](coroutine-builders)` → `[coroutine builders](#coroutine-builders)`.
- This ensures proper navigation within the same document.
Tested and confirmed that the link now correctly redirects to the intended section.
Let me know if any further modifications are needed. Thanks!
=> Fix broken internal link in coroutines.md (coroutine builders section)

proposals/common-atomics.md, proposals/stdlib/common-atomics.md
An issue for discussion and feedback: #398
=> Introduce Common Atomic and Atomic Array types in kotlin-stdlib

proposals/jvm-expose-boxed.md
Only comment here about the text itself. The discussion about the feature is done in https://github.com/Kotlin/KEEP/issues/394.
We propose modifications to how value classes are exposed in JVM, with the goal of easier consumption from Java. This includes exposing the constructor publicly and giving the ability to expose boxed variants of operations.
=> Expose boxed inline value classes in JVM

proposals/nested-typealias.md
Only comment here about the text itself. The discussion about the feature is done in #406.
Right now type aliases can only be used at the top level. The goal of this document is to propose a design to allow them within other classifiers, in case they do not capture any type parameters of the enclosing declaration.
=> Nested (non-capturing) type aliases

proposals/context-parameters.md
This PR includes clarifications and corrections found during the implementation. To be merged only once the initial implementation is released.
=> Refinements to "context parameters" KEEP
